Update sweep_fees for upgrade_authority
Bonfida/dex-v4 pull request #41
Opened 2022-03-16 05:06 UTC by sayantank

Updated the `sweep_fees` instruction to expect the `upgrade_authority` of the DEX program to sign the instruction.

2022-03-16 20:02 UTC, ellttBen requested changes

2022-03-17 04:45 UTC, sayantank commented on program/src/processor.rs
> +pub static SWEEP_AUTHORITY: Pubkey = sweep_authority::ID;
yup sure, i'll do that. Thanks!

2022-03-17 14:35 UTC, sayantank commented on program/src/processor.rs
> +pub static SWEEP_AUTHORITY: Pubkey = sweep_authority::ID;
Had to update `solana_program` to `1.10.2` to use the `pubkey!` macro. Hopefull shouldn't break anything

2022-03-22 11:28 UTC, ellttBen approved these changes

2022-03-22 11:47 UTC, merged